config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  resources :articles do
    resources :comments
  end
  resources :projects

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  has_many :comments

  def publish!
    published = true
    save!
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, foreign_key: 'author_id'
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :omniauthable

  def author?
    role == 'author'
  end

  def editor?
    role == 'editor'
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.nickname
      user.email = "#{user.name}-CHANGEME@twitter.example.com"
    end
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes'], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # protect_from_forgery except: :destroy
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = policy_scope(Article)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = Comment.new
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        current_user.articles << @article
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :body, (:published if current_user.role == 'editor'))
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = @article.comments.build(comments_params)
    if @comment.save
      flash[:notice] = 'Post submitted for approval'
      redirect_to articles_path
    else
      flash[:notice] = 'Comment not saved'
      redirect_to articles_path
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:author, :content,
                                    (:approved if current_user.present? &&
                                    (current_user.editor? || current_user.author?)))
  end

  def set_article
    @article = Article.find(params[:article_id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :body,
                                    (:published if current_user.role == 'editor'))
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def all
    user = User.from_omniauth(request.env['omniauth.auth'])
    if user.persisted?
      flash.notice = "#{user.name}, you are signed in!"
      sign_in_and_redirect user, notice: "#{user.name}, you are signed in!"
    else
      session['devise.user_attributes'] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects }
        format.js
      else
        format.html
        flash.now[:error] = 'Project could not be saved.'
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to @project, notice: 'Changes successfully saved'
    else
      flash.now[:error] = 'Changes not saved'
      render :edit
    end
  end

  def show
  end

  def destroy
    @project.destroy
    format.js
    redirect_to projects_path, notice: 'Project has been deleted'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  # rails flash levels to Foundation classes
  def flash_class(level)
    case level
    when :notice then 'info'
    when :success then 'success'
    when :error then 'error'
    when :alert then 'warning'
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_comment.html.erb
<%= form_for([@article, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_area :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <% if current_user.present? && (current_user.editor? || current_user.author?) %>
    <div class="row collapse">
      <div class="small-3 columns"
        <%= f.label :approved, class: "right inline", title: "Is this article approved?", data: {tooltip: true } %><br>
      </div>
      <div class="small-9 columns">
        <%= f.check_box :approved %>
      </div>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :class => 'ckeditor' %>
  </div>
 <% if current_user.role == 'editor' %>
  <div class="row collapse">
    <div class="small-3 columns"
      <%= f.label :published, class: "right inline", title: "Is this article published?", data: {tooltip: true } %><br>
    </div>
    <div class="small-9 columns">
      <%= f.check_box :published %>
    </div>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>
          <% if policy(article).update? %>
           <td><%= link_to 'Edit', edit_article_path(article) %></td>
           <% end %>
        <% if policy(article).destroy? %>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p id="author">
  <strong>By:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Body:</strong>
  <%= raw(@article.body) %>
</p>

<p id="status">
  <strong>Status:</b>
  <%= @article.published? ? 'Published' : 'Unpublished' %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<%= link_to 'New Article', new_article_path if current_user.role == 'editor' || 'author' %>

app/views/comments/edit.html.erb
<h1>Editing comments</h1>

<%= render 'articles/comment' %>

<%= link_to 'Show', article_comment_path %> |
<%= link_to 'Back', article_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Portfolio" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Portfolio" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
       <% if current_user.present? %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
       <% else %>
        <%= link_to 'Sign Up', new_user_registration_path %>
        <%= link_to 'Sign In', user_session_path %>
       <% end %>
        <div><!-- begin flash div -->
        <% flash.each do |key, value| %>
          <div class="alert-box round <%= flash_class(key) %>">
          <%= value %>
          </div>
        <% end %>
      </div><!-- end flash div -->
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project, remote: true) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, 'Name field must be filled out') %>
        prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/projects/create.js.erb
$('#new_link').remove();
$('#show_link').show();
$('#project').append('<%= j render(@project) %>');

app/views/projects/destroy.js.erb
$('#delete_link_<%= @project.id %>').remove();

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

<%= link_to 'Cancel', :back %>

app/views/projects/index.html.erb
<h2>Portfolio</h2>

<% @projects.each do |project| %>
  <div class="project" id="<%= dom_id(project) %>">
    <h3><%= project.name %></h3>
    <p><%= project.description %></p>
    <div class="nav">
      <%= link_to 'Show', project, id: "show_link", remote: true %> |
      <%= link_to 'Edit', edit_project_path(project), id: "edit_link", remote: true %> |
      <%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' }, id: "delete_link", remote: true %>
    </div>
  </div>
  <% end %>

  <br>
  <%= link_to 'Create New Project', new_project_path, id: "new_link", remote: true %>

app/views/projects/new.html.erb
<h2>New project</h2>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p>Description: <%=@project.description %></p>

app/views/welcome/index.html.erb
<h1>Deirdre Allison | Portfolio</h1>

<p>Hi! I'm a Web Developer currently located in Seattle, WA. I studied Digital Technology and Culture in college which sounds confusing but was a really awesome program focused on web design, graphic design and UX. I spent over three years working as a web producer before making the switch to web development.</p>

<h2>Some things I like:</h2>
<ul>
  <li>HTML5 &amp; CSS3</li>
  <li>Ruby on Rails</li>
  <li>Trail running</li>
  <li>Coffee</li>
  <li>And lots more!</li>
</ul>